name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: gcc-debug
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: gcc-debug
        uses: ./.github/actions/tcalib
        with:
          run-command: ".ci/build_gcc_debug.sh"
